googleinterns/step132-2020

src/main/webapp/registration.html
step132-2020/src/main/java/com/google/sps/servlets/RegistrationServlet.java
step132-2020/src/main/javatests/com/google/RegistrationTest.java
step132-2020/src/main/webapp/registration.css
step132-2020/src/main/webapp/registration.html
step132-2020/src/main/webapp/registration.js

These commits will create a basic registration page that allows students and tutors to sign up for our service. It will ask both students and tutors for their name and email, and tutors will be able to select the topic(s) they want to tutor in. For now, the backend will just immediately display the information that the user just inputted.

Basic Registration Page

---

pom.xml

These commits update the pom.xml artifactId to "sullivan".

Update pom.xml artifact ID

---

src/main/java/com/google/sps/servlets/RegistrationServlet.java
src/main/javatests/com/google/RegistrationTest.java
src/main/webapp/registration.css
src/main/webapp/registration.html
src/main/webapp/registration.js

These commits will fix the previous basic login commits so everything was initialized in the correct place.

Fix basic login

---

src/main/java/com/google/sps/data/TimeRange.java
src/main/java/com/google/sps/data/Tutor.java

These commits create two new classes, Tutor.java and TimeRange.java, which will be used to store tutor information. The Tutor class stores the name, email, skills, and availability of a tutor and the TimeRange class stores the start time, duration, and end time of a time range.

Create Tutor and TimeRange classes

---

src/main/java/com/google/sps/data/SampleData.java

These commits creates a new class containing sample Tutor objects for testing.

Create sample data for testing

---

pom.xml
src/main/java/com/google/sps/data/SampleData.java
src/main/java/com/google/sps/servlets/AvailabilityServlet.java
src/main/webapp/SpecRunner.html
src/main/webapp/availability.html
src/main/webapp/availability.js
src/main/webapp/webapptests/spec/SpecAvailability.js
src/test/java/com/google/sps/AvailabilityTest.java

The commits proposed in this PR allow the user to see the availability of a tutor and select a desired available time slot for a tutoring session. This procedure is handled by the AvailabilityServlet along with the added changes to availability.java. JavaScript and Java Unit tests are included.

Display availability

---

src/main/java/com/google/sps/data/SampleData.java

These commits make the data in SampleData.java static and create new methods for adding tutors, deleting tutors by email, and getting tutors by email.

Make sample data static

---

src/main/java/com/google/sps/data/SampleData.java
src/main/java/com/google/sps/data/Tutor.java
src/main/java/com/google/sps/data/TutorSession.java
src/main/java/com/google/sps/servlets/AvailabilityServlet.java

The changes proposed in this PR create the Session object class, which is responsible for handling information regarding a scheduled tutoring session. It also adds the scheduledSessions property to the Tutor object class, which is an array of Session and keeps track of all the sessions scheduled with that specific tutor.

Tutor Session Object Class

---

src/main/java/com/google/sps/servlets/SearchServlet.java
src/main/webapp/homepage.css
src/main/webapp/homepage.html
src/main/webapp/search-results.css
src/main/webapp/search-results.html
src/main/webapp/search.js
src/main/webapp/webapptests/spec/SpecSearch.js
src/test/java/com/google/sps/SearchTest.java

These commits implement the doGet method in the Search servlet so that it returns a list of Tutors for a searched topic, along with a few tests for the servlet. I also created search result elements for each result and displayed them in the result-container div. I updated the test for the result container and added tests for creating the result elements. Lastly, I added some styling using Bootstrap and CSS.

Add search functionality

---

src/main/java/com/google/sps/data/SampleData.java
src/main/java/com/google/sps/data/Student.java
src/main/java/com/google/sps/servlets/AvailabilityServlet.java
src/main/java/com/google/sps/servlets/ConfirmationServlet.java
src/main/java/com/google/sps/servlets/SchedulingServlet.java
src/main/webapp/confirmation.js
src/main/webapp/scheduling.js
src/main/webapp/webapptests/spec/SpecConfirmation.js
src/main/webapp/webapptests/spec/SpecScheduling.js
src/test/java/com/google/sps/ConfirmationTest.java
src/test/java/com/google/sps/SchedulingTest.java

The commits proposed in this PR implement the Student object class. Changes include creating the Student class, adding it to the Sample Data class along with appropriate functions, and adding the Student class to the Scheduling and Confirmation serlvets so that the student's scheduledSessions array is updated and so that a list of the student's upcoming sessions is displayed in the confirmation page.

Student Object Class

---

src/main/java/com/google/sps/data/SampleData.java
src/main/java/com/google/sps/data/Student.java
src/main/java/com/google/sps/data/Tutor.java
src/main/java/com/google/sps/servlets/AvailabilityServlet.java
src/main/java/com/google/sps/servlets/ConfirmationServlet.java
src/main/java/com/google/sps/servlets/SearchServlet.java
src/test/java/com/google/sps/SchedulingTest.java
src/test/java/com/google/sps/SearchTest.java

These features change the skills, availability, and tutor session arrays in the Tutor object to lists and the learning and sessions arrays in the Student object to lists. I have also updated tests and servlets to reflect this change. Changing these property arrays to lists will allow for easier adding and removing items and storing in datastore.

Change Tutor and Student property arrays to lists

---

src/main/java/com/google/sps/data/SampleData.java
src/main/java/com/google/sps/data/Student.java
src/main/java/com/google/sps/data/Tutor.java
src/main/java/com/google/sps/data/TutorSession.java
src/main/java/com/google/sps/servlets/HistoryServlet.java
src/main/java/com/google/sps/servlets/RatingServlet.java
src/main/java/com/google/sps/servlets/SearchServlet.java
src/main/webapp/SpecRunner.html
src/main/webapp/history.html
src/main/webapp/history.js
src/main/webapp/webapptests/spec/SpecHistory.js
src/main/webapp/webapptests/spec/SpecScheduling.js
src/test/java/com/google/sps/ConfirmationTest.java
src/test/java/com/google/sps/HistoryTest.java
src/test/java/com/google/sps/RatingTest.java
src/test/java/com/google/sps/SchedulingTest.java
src/test/java/com/google/sps/SearchTest.java

The commits proposed in this PR implement the rating a tutor feature. Changes include creating a page to see a tutoring session history, creating a history servlet to handle displaying a student's tutoring session history, and creating a rating servlet to rate a tutor.

Ratings final

---

src/main/java/com/google/sps/servlets/LoginStatusServlet.java
src/main/java/com/google/sps/servlets/RegistrationServlet.java
src/main/webapp/availability.html
src/main/webapp/confirmation.html
src/main/webapp/general.css
src/main/webapp/homepage.html
src/main/webapp/registration.html
src/main/webapp/registration.js
src/main/webapp/scheduling.html
src/main/webapp/search-results.html
src/main/webapp/webapptests/spec/SpecRegistration.js
src/test/java/com/google/sps/LoginStatusTest.java
src/test/java/com/google/sps/RegistrationTest.java

These commits will integrate the many features we've been working on. This will make it so the user can navigate the site easily without having to manually change the URL. Commits will include adding things like a homepage and login/logout link to every page. When a user logs in or out, the webapp should navigate them back to the page they were previously on.

Feature Integration

---

src/main/java/com/google/sps/servlets/RegistrationServlet.java
src/test/java/com/google/sps/RegistrationTest.java

These commits update the registration servlet and tests to follow the table per type method outlined on the Datastore User Information Structure design doc. The User entity will store the role and id of the user while the Tutor and Student entities will store more information.

Update registration servlet user information storage

---

src/main/webapp/history.html

These commits will add a homepage link and login/logout link to the history page.

Integrate history page with other features

---

src/main/webapp/availability.js
src/main/webapp/confirmation.js
src/main/webapp/history.js
src/main/webapp/webapptests/spec/SpecAvailability.js
src/main/webapp/webapptests/spec/SpecConfirmation.js
src/main/webapp/webapptests/spec/SpecHistory.js

The commits proposed in this PR format the time slot boxes in the availability, confirmation, and history pages. Changes include adding complete information about a time slot/tutoring session such as date, time, and tutor name.

Time slot box format

---

src/main/java/com/google/sps/data/SampleData.java
src/main/java/com/google/sps/data/Tutor.java
src/main/java/com/google/sps/servlets/AddAvailabilityServlet.java
src/main/java/com/google/sps/servlets/DeleteAvailabilityServlet.java
src/main/java/com/google/sps/servlets/HistoryServlet.java
src/main/java/com/google/sps/servlets/RatingServlet.java
src/main/java/com/google/sps/servlets/SchedulingServlet.java
src/main/java/com/google/sps/utilities/MockAvailabilityDatastore.java
src/main/java/com/google/sps/utilities/MockRatingDatastore.java
src/main/java/com/google/sps/utilities/MockStudentsDatastore.java
src/main/java/com/google/sps/utilities/MockTutorDatastore.java
src/main/java/com/google/sps/utilities/MockTutorSessionDatastore.java
src/main/java/com/google/sps/utilities/RatingDatastoreService.java
src/main/java/com/google/sps/utilities/RealRatingDatastore.java
src/main/java/com/google/sps/utilities/RealStudentsDatastore.java
src/main/java/com/google/sps/utilities/RealTutorDatastore.java
src/main/java/com/google/sps/utilities/StudentsDatastoreService.java
src/main/java/com/google/sps/utilities/TutorDatastoreService.java
src/main/webapp/SpecRunner.html
src/main/webapp/manage-availability.html
src/main/webapp/manage-availability.js
src/main/webapp/webapptests/spec/SpecManageAvailability.js
src/test/java/com/google/sps/AddAvailabilityTest.java
src/test/java/com/google/sps/AvailabilityTest.java
src/test/java/com/google/sps/ConfirmationTest.java
src/test/java/com/google/sps/DeleteAvailabilityTest.java
src/test/java/com/google/sps/HistoryTest.java
src/test/java/com/google/sps/RatingTest.java
src/test/java/com/google/sps/SchedulingTest.java
src/test/java/com/google/sps/SearchTest.java

The commits proposed in this PR implement the manage-availability page, where the tutor can delete or add new available time slots to their availability, Changes include creating a servlet to handle adding new time slots and a servlet to handle deleting time slots, creating the js file with the functions for this new page, and all the necessary test files.

Edit availability

---

src/main/java/com/google/sps/servlets/IndexServlet.java

The commit proposed in this PR creates the index servlet. which is responsible for redirecting the user to the homepage once it the project is loaded. Before this change, the user would get a "page not found" error since the index.html file was not set.

Redirect User to Homepage

---

src/main/java/com/google/sps/data/LoginStatus.java
src/main/java/com/google/sps/servlets/LoginStatusServlet.java
src/main/webapp/availability.html
src/main/webapp/confirmation.html
src/main/webapp/history.html
src/main/webapp/history.js
src/main/webapp/homepage.html
src/main/webapp/manage-availability.html
src/main/webapp/manage-availability.js
src/main/webapp/profile.html
src/main/webapp/profile.js
src/main/webapp/registration.js
src/main/webapp/scheduling.html
src/main/webapp/search-results.html
src/main/webapp/webapptests/spec/SpecRegistration.js
src/test/java/com/google/sps/LoginStatusTest.java

The changes proposed in this PR connect the manage availability page and the history page to the rest of the project. Buttons to access the manage availability and history pages are displayed in the profile page if the user is logged in. For now, the user's email is passed down to the manage availability and history pages (but in the future we aim to have the user id be passed down). Therefore, a field called userEmail has been added to the LoginStatus object class. Jasmine tests for registration.js and java tests for LoginStatusServlet have been updated to reflect these changes.

Connect availability setting and history to profile page

---

src/main/webapp/profile.js
src/main/webapp/webapptests/spec/SpecSearch.js

These commits will fix the edit profile feature so that pre-selected topics will stay checked when edited your profile. I also fixed a frontend test for the search feature.

Fix topics

---

src/main/webapp/profile.js

The commit proposed in this PR fixes an issue with the way the profile page was being displayed. The progress tracker should only be displayed if the user is a student, else only display the profile.

Fix Profile Display

---

src/main/webapp/registration.js
src/main/webapp/webapptests/spec/SpecProfile.js
src/main/webapp/webapptests/spec/SpecRegistration.js

These commits fix a few errors in the Jasmine tests for the profile and registration page. For the profile, the createProfileDiv call was missing a mock login status and there was a problem adding event listeners to certain elements. For the registration page, I updated the logout link test as we are not using the url provided by the Authentication API anymore.

Jasmine test fixes

---

src/main/webapp/availability.js
src/main/webapp/confirmation.js
src/main/webapp/history.js
src/main/webapp/manage-availability.js
src/main/webapp/manage-sessions.js
src/main/webapp/my-students.js
src/main/webapp/webapptests/spec/SpecConfirmation.js
src/main/webapp/webapptests/spec/SpecManageSessions.js
src/main/webapp/webapptests/spec/SpecMyStudents.js
src/main/webapp/webapptests/spec/SpecProfile.js

The commits proposed in this PR make sure that a message saying "no results for a given user were returned" is displayed. Jasmine tests have been updated to reflect the changes.

Display No Results Messages

---

src/main/webapp/confirmation.html
src/main/webapp/profile.html
src/main/webapp/profile.js

The commits proposed in this PR alter some of the text alignment options so that they comply with the overarching UI of the web app.

Adjust text alignment options

---

src/main/webapp/availability.js
src/main/webapp/confirmation.js
src/main/webapp/history.js
src/main/webapp/manage-availability.js
src/main/webapp/manage-sessions.js
src/main/webapp/profile.js
src/main/webapp/progress.js

These commits change how we edit the text of an HTML element. Instead of using .innerHTML, we have to use .innerText to prevent HTML injection.

Switch innerHTML to innerText

---

src/main/webapp/profile.html
src/main/webapp/profile.js

These changes change the text inside the profile from left-aligned to centered.

Center Text in Profile

---

src/main/java/com/google/sps/servlets/ManageAvailabilityServlet.java
src/main/webapp/SpecRunner.html
src/main/webapp/availability.html
src/main/webapp/availability.js
src/main/webapp/confirmation.html
src/main/webapp/confirmation.js
src/main/webapp/manage-availability.html
src/main/webapp/manage-availability.js
src/main/webapp/manage-sessions.html
src/main/webapp/manage-sessions.js
src/main/webapp/webapptests/spec/SpecAvailability.js
src/main/webapp/webapptests/spec/SpecConfirmation.js
src/main/webapp/webapptests/spec/SpecManageAvailability.js
src/main/webapp/webapptests/spec/SpecManageSessions.js
src/test/java/com/google/sps/ManageAvailabilityTest.java

These commits will add update the calendar display and functionality. Changes will include adding a calendar to the availability page, automatically making tutor sessions 1 hour long, adding tutor names to rows on the manage sessions page, making the calendar display dates in chronological order, and adding event listeners to sessions so you can delete and schedule sessions directly from the calendar.

Update calendar and availability 

---

src/main/webapp/registration.html

The commits proposed in this PR add line breaks and change font size in the registration form,

Add line breaks to the registration page

---

src/main/webapp/profile.html
src/main/webapp/progress.js
src/main/webapp/webapptests/spec/SpecProfile.js
src/main/webapp/webapptests/spec/SpecProgress.js

The commits proposed in this PR remove achievements from the progress tracker and centers the error messages. It also updates some issues that had come up with the jasmine tests.

Update Progress Tracker

---

src/main/webapp/availability.html
src/main/webapp/confirmation.html
src/main/webapp/group.html
src/main/webapp/groups.html
src/main/webapp/history.html
src/main/webapp/homepage.html
src/main/webapp/manage-availability.html
src/main/webapp/manage-sessions.html
src/main/webapp/my-lists.html
src/main/webapp/my-students.html
src/main/webapp/profile.html
src/main/webapp/registration.html
src/main/webapp/registration.js
src/main/webapp/scheduling.html
src/main/webapp/search-results.html
src/main/webapp/search-user-results.html
src/main/webapp/webapptests/spec/SpecRegistration.js

The commits proposed in this PR add a button that redirects the user to the groups page to the navigation bar in all pages.  The redirectToGroups function has been added to registration.js and the necessary jasmine tests have been updated.

Add Groups to Nav Bar

---

src/main/java/com/google/sps/servlets/GoogleBooksServlet.java
src/main/webapp/search.js
src/main/webapp/webapptests/spec/SpecSearch.js

These commits create a new servlet called GoogleBooksServlet that fetches books data with the parameters passed from JavaScript fetch requests. I updated the JavaScript fetch calls from the API to the new servlet, so the API key is no longer exposed in the front end. Instead I stored the key in an environment variable in Cloud Shell. 
I also added a Jasmine test for the load more books function. 
I will update mylists.js after my other PR is merged so that it makes a request to the servlet instead of the API directly. I will also work on the servlet test later as it will take me some time to figure out how exactly to test it. We needed to hide the API key ASAP, so I thought it would be better to submit a PR without a test for now.

Fetch Google Books data through servlet

---

src/main/webapp/group.js
src/main/webapp/groups.html
src/main/webapp/groups.js
src/main/webapp/search-users.js
src/main/webapp/webapptests/spec/SpecGroup.js
src/main/webapp/webapptests/spec/SpecGroups.js

These commits fix the id issue for the groups.html page. I've also updated a few Jasmine tests for the groups and group pages that I missed before.

Fix Groups nav bar issue and update Jasmine tests

---

src/main/webapp/my-students.js
src/main/webapp/webapptests/spec/SpecMyStudents.js

The commit proposed in this PR deletes the trailing commas in the "learning" section of the my students page. I have also updated the jasmine tests for it.

Delete Trailing Commas in My Students

---

src/main/webapp/general.js
src/main/webapp/webapptests/spec/SpecHistory.js

The tutor name was being displayed as undefined in history because history was not checking whether the tutor is also a student or not. Now that it makes that distinction it correctly displays the name of the tutor. I also added a new jasmine test to check this.

Make sure the tutor is not undefined in history

---

src/main/java/com/google/sps/servlets/GoogleBooksServlet.java
src/test/java/com/google/sps/GoogleBooksServletTest.java

These commits create a test class for the GoogleBooksServlet class. I separated the doGet method in the servlet into smaller helper methods so we could spy on the helper methods (like we did in the Jasmine tests).

Add test for GoogleBooksServlet

---

src/main/webapp/homepage.html

The commits proposed in this PR add additional information to the homepage that gives the user a better sense of what they can do with Sullivan.

Update the Homepage with Additional Information

---

src/main/webapp/confirmation.js
src/main/webapp/history.js
src/main/webapp/manage-availability.js
src/main/webapp/manage-sessions.js
src/main/webapp/my-students.js

The text of an undefined element was being set to the message rather than, so the message was not displayed on the page.

Fix messages not displaying when there is an error or no results found
